name: my primer workflow - JS

on:
  push:
    branches:
      - Release

  pull_request:
    branches:
      - Release

  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Ejecutar pruebas unitarias
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas
        run: npm test